### ISSUE TITLE
Hangs on 2023-02-13 17:01:51.832 Loading pretrained files for: embedding_model, mean_var_norm_emb, classifier, label_encoder

### ISSUE THREAD

**Issue by TheRealAlexV** [mave5/podalize#7]
Hi there. I'm trying to transcribe an MP3 and found that podalize is hanging on:
2023-02-13 17:01:51.832 Loading pretrained files for: embedding_model, mean_var_norm_emb, classifier, label_encoder

**Comment by TheRealAlexV** [comment]
Just tried this on a fresh Ubuntu 22.04 vm and it hangs at the same spot.

**Comment by TheRealAlexV** [comment]
Finally got to a timeout:

```
2023-02-14 00:53:42.315 Created a temporary directory at /tmp/tmpuyysaz2v
2023-02-14 00:53:42.315 Writing /tmp/tmpuyysaz2v/_remote_module_non_sriptable.py
2023-02-14 00:53:42.342 Fetch hyperparams.yaml: Delegating to Huggingface hub, source speechbrain/spkrec-ecapa-voxceleb.
2023-02-14 00:53:42.435 Fetch custom.py: Delegating to Huggingface hub, source speechbrain/spkrec-ecapa-voxceleb.
2023-02-14 00:53:42.662 Fetch embedding_model.ckpt: Using existing file/symlink in /root/.cache/torch/pyannote/speechbrain/embedding_model.ckpt.
2023-02-14 00:53:42.662 Fetch mean_var_norm_emb.ckpt: Using existing file/symlink in /root/.cache/torch/pyannote/speechbrain/mean_var_norm_emb.ckpt.
2023-02-14 00:53:42.662 Fetch classifier.ckpt: Using existing file/symlink in /root/.cache/torch/pyannote/speechbrain/classifier.ckpt.
2023-02-14 00:53:42.662 Fetch label_encoder.txt: Using existing file/symlink in /root/.cache/torch/pyannote/speechbrain/label_encoder.ckpt.
2023-02-14 00:53:42.662 Loading pretrained files for: embedding_model, mean_var_norm_emb, classifier, label_encoder
2023-02-14 00:57:26.191 Uncaught app exception
Traceback (most recent call last):
  File "/root/anaconda3/envs/podalize/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "/root/podalize/podalize_app.py", line 63, in <module>
    result = get_transcript(model_size=model_size,
  File "/root/podalize/myutils.py", line 116, in get_transcript
    model = whisper.load_model(model_size)
AttributeError: module 'whisper' has no attribute 'load_model'

```

**Comment by mave5** [comment]
Make sure that you are using the same version of whisper==1.0 listed in the environment.yml file.

**Comment by hamisus** [comment]
I'm also having it hang on the same line. Running mac m1. Have installed whisper==1.0

`2023-03-09 15:12:46.665 Fetch hyperparams.yaml: Delegating to Huggingface hub, source speechbrain/spkrec-ecapa-voxceleb.
2023-03-09 15:12:47.016 Fetch custom.py: Delegating to Huggingface hub, source speechbrain/spkrec-ecapa-voxceleb.
2023-03-09 15:12:47.450 Fetch embedding_model.ckpt: Using existing file/symlink in /Users/adam/.cache/torch/pyannote/speechbrain/embedding_model.ckpt.
2023-03-09 15:12:47.451 Fetch mean_var_norm_emb.ckpt: Using existing file/symlink in /Users/adam/.cache/torch/pyannote/speechbrain/mean_var_norm_emb.ckpt.
2023-03-09 15:12:47.451 Fetch classifier.ckpt: Using existing file/symlink in /Users/adam/.cache/torch/pyannote/speechbrain/classifier.ckpt.
2023-03-09 15:12:47.451 Fetch label_encoder.txt: Using existing file/symlink in /Users/adam/.cache/torch/pyannote/speechbrain/label_encoder.ckpt.
2023-03-09 15:12:47.451 Loading pretrained files for: embedding_model, mean_var_norm_emb, classifier, label_encoder`

**Comment by hamisus** [comment]
Update - turns out it was just taking a REALLY long time. Left it running over night and it succeeded successfully. Guessing since I'm running mac m1 that I need to do some tinkering with the torch/cuda stuff, as by default it says cuda is not available.

**Comment by hamisus** [comment]
Also the transcript it outputted was pretty much spot on, awesome script you've built.
